#!/bin/bash

# Local Supabase Setup Script for Sailorskills
# Initializes local Supabase, pulls production schema, and configures for development

set -e

# Colors for output
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}Sailorskills Local Supabase Setup${NC}"
echo -e "${BLUE}================================${NC}"
echo ""

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo -e "${RED}Error:${NC} Supabase CLI not found"
    echo ""
    echo "Install with:"
    echo "  ${BLUE}brew install supabase/tap/supabase${NC}"
    echo ""
    echo "Or visit: https://supabase.com/docs/guides/cli"
    exit 1
fi

SUPABASE_VERSION=$(supabase --version)
echo -e "${GREEN}✓${NC} Supabase CLI installed: $SUPABASE_VERSION"
echo ""

# Check if already initialized
if [ -d "supabase" ]; then
    echo -e "${YELLOW}⚠${NC}  Supabase already initialized"
    read -p "Do you want to reinitialize? (This will delete existing config) [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Removing existing Supabase directory..."
        rm -rf supabase
    else
        echo "Using existing Supabase configuration"
        echo ""
    fi
fi

# Initialize if needed
if [ ! -d "supabase" ]; then
    echo -e "${YELLOW}Step 1/5: Initializing Supabase...${NC}"
    supabase init
    echo -e "${GREEN}✓${NC} Supabase initialized"
    echo ""
fi

# Start Supabase
echo -e "${YELLOW}Step 2/5: Starting Supabase...${NC}"
supabase start
echo -e "${GREEN}✓${NC} Supabase started"
echo ""

# Get local credentials
echo -e "${YELLOW}Step 3/5: Getting local credentials...${NC}"
API_URL=$(supabase status | grep "API URL" | awk '{print $3}')
ANON_KEY=$(supabase status | grep "anon key" | awk '{print $3}')
SERVICE_KEY=$(supabase status | grep "service_role key" | awk '{print $3}')
STUDIO_URL=$(supabase status | grep "Studio URL" | awk '{print $3}')

echo -e "${GREEN}✓${NC} Local Supabase credentials retrieved"
echo ""
echo "  API URL: ${BLUE}$API_URL${NC}"
echo "  Studio URL: ${BLUE}$STUDIO_URL${NC}"
echo ""

# Pull production schema (if remote connection available)
echo -e "${YELLOW}Step 4/5: Pulling production schema...${NC}"

if [ -f ".env.local" ]; then
    source .env.local

    # Check if remote Supabase URL is configured
    if [[ "$VITE_SUPABASE_URL" == *"supabase.co"* ]]; then
        echo "Found remote Supabase URL: $VITE_SUPABASE_URL"

        # Extract project ref from URL
        PROJECT_REF=$(echo $VITE_SUPABASE_URL | sed -E 's/https:\/\/(.+)\.supabase\.co/\1/')

        read -p "Do you want to pull schema from production? [Y/n]: " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Nn]$ ]]; then
            echo "Linking to remote project..."
            supabase link --project-ref "$PROJECT_REF" || {
                echo -e "${YELLOW}⚠${NC}  Failed to link project - you may need to login first"
                echo "  Run: ${BLUE}supabase login${NC}"
                echo "  Then rerun this script"
            }

            echo "Pulling database schema..."
            supabase db pull || {
                echo -e "${YELLOW}⚠${NC}  Failed to pull schema - continuing with empty database"
            }
        fi
    else
        echo -e "${YELLOW}⚠${NC}  No remote Supabase URL found in .env.local"
        echo "  Starting with empty database"
    fi
else
    echo -e "${YELLOW}⚠${NC}  No .env.local file found"
    echo "  Starting with empty database"
fi
echo ""

# Create .env.local.supabase for local development
echo -e "${YELLOW}Step 5/5: Creating local environment file...${NC}"

cat > .env.local.supabase << EOF
# Local Supabase Configuration
# Generated by setup-local-supabase.sh on $(date)
#
# To use local Supabase, copy these values to .env.local
# Or run: source .env.local.supabase

VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_KEY=$SERVICE_KEY

# Database connection string (for migrations, testing, scripts)
# Format: postgresql://postgres:postgres@localhost:54322/postgres
DATABASE_URL=postgresql://postgres:postgres@localhost:54322/postgres
EOF

echo -e "${GREEN}✓${NC} Created .env.local.supabase"
echo ""

# Summary
echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}Setup Complete!${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo "Local Supabase is running:"
echo "  - API: ${BLUE}$API_URL${NC}"
echo "  - Studio: ${BLUE}$STUDIO_URL${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Update your .env.local to use local Supabase:"
echo "   ${BLUE}cat .env.local.supabase >> .env.local${NC}"
echo ""
echo "2. Or load local environment temporarily:"
echo "   ${BLUE}source .env.local.supabase${NC}"
echo ""
echo "3. View Supabase Studio in browser:"
echo "   ${BLUE}open $STUDIO_URL${NC}"
echo ""
echo "4. Check Supabase status:"
echo "   ${BLUE}supabase status${NC}"
echo ""
echo "5. Stop Supabase when done:"
echo "   ${BLUE}supabase stop${NC}"
echo ""
echo "6. Start services with local database:"
echo "   ${BLUE}./scripts/start-dev.sh all${NC}"
echo ""
