name: Integration Tests

on:
  # Run on pull requests to main
  pull_request:
    branches: [main]

  # Run on pushes to main
  push:
    branches: [main]

  # Allow manual trigger
  workflow_dispatch:

  # Run nightly to catch regressions
  schedule:
    - cron: '0 6 * * *' # 6 AM UTC daily

jobs:
  integration-tests:
    name: Cross-Service Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run integration tests
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          CI: true
        run: npm run test:integration

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7

  # Optional: Send notifications on failure
  notify-on-failure:
    name: Notify on Test Failure
    runs-on: ubuntu-latest
    needs: integration-tests
    if: failure()
    steps:
      - name: Send notification
        run: |
          echo "Integration tests failed!"
          echo "View results at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          # TODO: Add actual notification (Slack, email, etc.)
